const logsData = [
  {
    date: '3/4/2024',
    time: '2:14 AM',
    activityResult: 'Pending',
    relatedUser: 'عصام معتز بشير',
    activityType: 'اضافة وصفة طبية',
    username: 'محمد احمد عماد',
    userRole: 'طبيب',
  },
  {
    date: '3/4/2024',
    time: '2:14 AM',
    activityResult: 'Fail',
    relatedUser: 'يوسف عيسى موسى',
    activityType: 'انشاء فاتورة',
    username: 'احمد سيف محمد',
    userRole: 'موظف استقبال',
  },
  {
    date: '7/25/2024',
    time: '2:14 AM',
    activityResult: 'Completed',
    relatedUser: 'احمد محمد مصطفى',
    activityType: 'صرف وصفة',
    username: 'ابراهيم محمد خليل',
    userRole: 'صيدلاني',
  },
  {
    date: '7/25/2024',
    time: '2:14 AM',
    activityResult: 'Pending',
    relatedUser: 'نور علي احمد',
    activityType: 'اضافة مريض',
    username: 'امنة محمد احمد',
    userRole: 'موظف استقبال',
  },
  {
    date: '8/25/2024',
    time: '2:14 AM',
    activityResult: 'Fail',
    relatedUser: 'بلقيس محمود محمد',
    activityType: 'اصدار هوية',
    username: 'فرح عمر عيدان',
    userRole: 'مسؤول الهوية',
  },
  {
    date: '8/25/2024',
    time: '2:14 AM',
    activityResult: 'Completed',
    relatedUser: 'يوسف يعقوب اسحاق',
    activityType: 'اضافة موظف',
    username: 'مريم احمد محمد',
    userRole: 'الآدمن',
  },
  {
    date: '8/25/2024',
    time: '2:14 AM',
    activityResult: 'Fail',
    relatedUser: '-----',
    activityType: 'تسجيل دخول',
    username: 'نور يوسف سلمان',
    userRole: 'طبيب',
  },
  {
    date: '8/25/2024',
    time: '2:14 AM',
    activityResult: 'Completed',
    relatedUser: 'يوسف يعقوب اسحاق',
    activityType: 'حذف مريض',
    username: 'اية داوود سعد',
    userRole: 'موظف استقبال',
  },
  {
    date: '6/25/2024',
    time: '2:14 AM',
    activityResult: 'Pending',
    relatedUser: 'طلحة خالد حسين',
    activityType: 'حذف فاتورة',
    username: 'ماريا خالد محمد',
    userRole: 'موظف استقبال',
  },
  {
    date: '8/25/2024',
    time: '2:14 AM',
    activityResult: 'Completed',
    relatedUser: 'اسحاق صقر محمد',
    activityType: 'طباعة فاتورة',
    username: 'نارين محمد عيسى',
    userRole: 'موظف استقبال',
  },
  {
    date: '8/25/2024',
    time: '2:14 AM',
    activityResult: 'Completed',
    relatedUser: 'صخر محمد احمد',
    activityType: 'الغاء وصفة',
    username: 'فرح محمد نور',
    userRole: 'طبيب',
  },
  {
    date: '8/25/2024',
    time: '2:14 AM',
    activityResult: 'Completed',
    relatedUser: 'ضرغام محمد ابراهيم',
    activityType: 'اضافة منتج',
    username: 'ايمن حسين عبد الله',
    userRole: 'أمين المخزن',
  },
];

export default logsData;
